### ISSUE TITLE
🐞 [BUG] - Issuer key is a invalid format.

### ISSUE THREAD

**Issue by Guy-Heylens-Elia** [project-origin/registry#123]
### Describe the Bug

Hello,

I am trying to setup Project Origin on an Azure K8S environment for development.
For this I use the HELM charts and this guide (https://artifacthub.io/packages/helm/project-origin/project-origin-registry).

According the guide we need to create an issuer key and put the PublicKey in the values file.
I have tried to create an issuer key on several machines, but with no success.

### To Reproduce

```bash
1. Create an issuer key, like described here (https://artifacthub.io/packages/helm/project-origin/project-origin-registry)
2. Create a values YML file and fill all necessary fields.
3. Goto portal.azure.com and log in.
4. Connect to your K8S in a new Cloud Shell.
5. Upload the values.yml file.
6. Execute the helm chart command.
```

### Expected Behavior

Verifier boots up and starts running.

### Screenshots

![image](https://github.com/project-origin/registry/assets/104833610/445dfeee-58c6-4ac5-ae8a-e8d1a80f6969)

![image](https://github.com/project-origin/registry/assets/104833610/4c841fd1-b731-4856-9846-765123019a3c)

### Desktop

K8S on Azure

**Comment by michaelpiron** [comment]
Hi @duizer @wisbech @MartinSchmidt , we are a bit stuck in the deployment of the PO registry in our K8S environment. My colleague Guy entered into the issue above. Would you be able to help us out?
Thanks.
Best, Michaël

**Comment by MartinSchmidt** [comment]
hi @Guy-Heylens-Elia and  @michaelpiron 
I would need some additional information to try and help you out, since the public-key is not something that must be private, could you share a snippet of your values file containing the public-key?

**Comment by wisbech** [comment]
Hi @Guy-Heylens-Elia - maybe this is just a shot in the dark, but apparently yaml is quite iffy about quotes dependent on the content this thread on [stackoverflow](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml#22235064). So try with a double quote

```
issuers:
  - area: BE1
    publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWRkZjg5aUdybDFTN0pBMDBNZDRKVEJHOEV1VkNCeXFlSVNLTXFYdXBuY2s9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
```
![image](https://github.com/project-origin/registry/assets/3016694/e07e34bc-8b92-48b0-977a-c1f9ac41fc22)

**Comment by Guy-Heylens-Elia** [comment]
> Hi @Guy-Heylens-Elia - maybe this is just a shot in the dark, but apparently yaml is quite iffy about quotes dependent on the content this thread on [stackoverflow](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml#22235064). So try with a double quote
> 
> ```
> issuers:
>   - area: BE1
>     publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWRkZjg5aUdybDFTN0pBMDBNZDRKVEJHOEV1VkNCeXFlSVNLTXFYdXBuY2s9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo="
> ```
> 
> ![image](https://user-images.githubusercontent.com/3016694/257203307-e07e34bc-8b92-48b0-977a-c1f9ac41fc22.png)

Correct, even with double quotes around the public key, it does not work. Still the same error.

**Comment by MartinSchmidt** [comment]
@Guy-Heylens-Elia 

The issue itself does not seam to be with the public-key, i made the following values.yaml file

```yaml
service:
  type: ClusterIP

verifiers:
  - name: electricity-v1
    type: project_origin.electricity.v1
    image:
      repository: ghcr.io/project-origin/electricity-server
      tag: 0.2.0-rc.17
    issuers:
        # the name of the grid area, here Narnia is used
      - area: BE1
        # the base64 encoded public key of the issuer
        publicKey: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUNvd0JRWURLMlZ3QXlFQWRkZjg5aUdybDFTN0pBMDBNZDRKVEJHOEV1VkNCeXFlSVNLTXFYdXBuY2s9Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=

    # if you want to use multiple registries, then ALL verifiers must know all registries External url
    # this is because the verifiers will use the external url to communicate with the registries
    registries:
      - name: my-example-registry
        address: http://my-example-registry:80
```

and tried to install it from helm into a kind cluster

```shell
kind create cluster
helm install test project-origin-registry --repo https://project-origin.github.io/helm-registry --version 0.2.0-rc.4 -f values.yaml 
```

and the result of the containers running:

![image](https://github.com/project-origin/registry/assets/7533429/25f30747-cbbf-4349-8cef-e3e5f5f9b6ff)

So i think the issue might be with either the chart version or the electricity-server version within the yaml file.
